### ISSUE TITLE
As a new user I want to get in to main page

### ISSUE THREAD

**Issue by ivxvi12** [ivxvi12/picture-to-music-ai#1]
This is the main page.

Please use [shadcn](https://ui.shadcn.com/) for button component.

design [figma](https://www.figma.com/file/GDPXZoW6FtRZOJvHXavGDN/MT?type=design&node-id=0%3A1&mode=design&t=0vqNKc44ONCDwHRT-1)
<img width="195" alt="image" src="https://github.com/ivxvi12/picture-to-music-ai/assets/9732616/df859b69-ec8f-4963-8e02-529b708d3b41">

**Comment by axel-gcd** [comment]
https://github.com/ivxvi12/picture-to-music-ai/pull/4
