### ISSUE TITLE
As an user I want to get transcripted text as a button and select or deselect.

### ISSUE THREAD

**Issue by ivxvi12** [ivxvi12/picture-to-music-ai#6]
This is the /emotions page.

Please use [shadcn](https://ui.shadcn.com/) for button component.

Returned words will appear as buttons on FE emotions page.
User can select or deselect words (buttons) to submit to get final generated music output.

design [figma](https://www.figma.com/file/GDPXZoW6FtRZOJvHXavGDN/MT?type=design&node-id=0%3A1&mode=design&t=0vqNKc44ONCDwHRT-1)
image
<img width="197" alt="image" src="https://github.com/ivxvi12/picture-to-music-ai/assets/9732616/6de26d2e-5f2d-4011-b128-0d2784be5704">

**Comment by axel-gcd** [comment]
https://github.com/ivxvi12/picture-to-music-ai/pull/7
